### ISSUE TITLE
how to handle auto disconnection due to timeout.

### ISSUE THREAD

**Issue by rajeshthb** [ice-services/moleculer#108]
Icebob,

Thanks for the great library. I exploring using your library for micro service implementation in our node server. 
I have node express server(service-routes) which is calling different services through service-master to get response from backend.

In case backend service-master takes longer than expected time. Express side of service broker is getting disconnect event. Same things happens to the other part of broker as seen below logs.

[2017-09-25T13:08:25.433Z] WARN  service-routes/TRANSIT: Node 'service-master' disconnected!
[2017-09-25T13:08:36.269Z] WARN  service-master/TRANSIT: Node 'service-routes' disconnected!

Now any new call to service actions will be lead to service not available error even though service is up. If I restart express side of server, it will again be back to normal. see below logs for service not available error.

[2017-09-25T13:18:29.573Z] WARN  service-routes/BROKER: Service 'test-feedback-svc.getquestions' is not available!
 broker-connectiontest-feedback-svc.getquestions broker failed Service 'test-feedback-svc.getquestions' is not available!

- Is there any way to increase time out ?
- how does one ensure that timeout in one service call doesnt impact other service calls. is handled automatically ?
- how to add re-connection code in disconnect event.

Thanks,
Rajesh

**Comment by icebob** [comment]
Hi Rajesh,

which version are you using? 0.11?
Could you make a simple repro repo that I can test it?

Thanks!

**Comment by rajeshpachar** [comment]
Hi @icebob,

Yes, I was using latest version.
I will try recreate a simple repro steps. the way i did was :

- client: calls service
- service: receives the call. but blocks it for some time(around a min) using break point in visual studio code. client doesn't return result.
- client: now believes service is disconnected. may be due to heart beat not responding.
- service: release the break point and let it run. 
- client: never attempts to reconnect the service. even though service is alive and running.

I have tried to recreate scenario with break point, but in production scenario, this may happen due to any other issue.

Thanks,
Rajesh

**Comment by icebob** [comment]
Thanks, I will try it.

**Comment by icebob** [comment]
Hi @rajeshpachar 
I tested but it's working properly. I tried with [server](https://github.com/ice-services/moleculer/blob/master/dev/server.js) & [client](https://github.com/ice-services/moleculer/blob/master/dev/client.js) example in dev.

**Comment by rajeshpachar** [comment]
@icebob 
Thanks for looking into it. Let me see if I can create a standalone repro.

**Comment by icebob** [comment]
Please reopen if you still have problem with it
