### ISSUE TITLE
Redundant service registration-Auto service versioning.

### ISSUE THREAD

**Issue by qdoop** [ice-services/moleculer#60]
What happens if we register multiple times the same service name with different schema?
(currently seems the latest registered schema wins)
Would it be usefull to have the hash of the loaded schema reported for each service?
Is it safe to register services on the fly (without stoping restarting the broker)?

In examples/user.service.js there is a flag latestVersion: true. Any plans to use semantic versioning in order
to implicitly peek a service version (like stable or latest) as default?

**Comment by icebob** [comment]
Currently the Moleculer is not ready to register a service multiple times on a node. The `version` of service is [implemented](http://moleculer.services/docs/service.html#Schema). In this case the version will be prefix in action names. E.g. `v1.users.list`, `v2.users.list`...etc

You can't register services after broker started, because it won't publish them to the other nodes.
But I plan I will implement a hot-plug mode. It will able to handle the "on the fly" registering and you will able to use it to re-register a service if it changed (hot-reload in development).

**Comment by qdoop** [comment]
Thanks for the repply.
What I like the most in this project is that you try to keep things minimal (Keep It Simple Stupid principle)
FYI  I have developed a similar platform where you submit code for execution on the fly dynamically (function blocks which get evaluated using eval on first execution and then cached).  A key feature is that calls to other functions get yielded allowing to  serialize async code execution like this
```
function sampleEval Fun(ctx){

     var x1= AWAIT ctx.call('getNumber1'); /*async call which returns a number */

    var x2= AWAIT ctx.call('getNumber2'); /*similar*/

     return x1+x2;
}
```
so when functions return there are no pendind operations  (https://www.promisejs.org/generators/)

**Comment by icebob** [comment]
In the new release you can register/unregister services after broker started. https://github.com/ice-services/moleculer/releases/tag/v0.9.0
